### ISSUE TITLE
project currently fails on python3.11

### ISSUE THREAD

**Issue by mimir-d** [opencomputeproject/ocp-diag-pci_lmt#3]
- we should support all newer python versions, 3.8-3.10 work but 3.11 fails as follows

```
> python3.11 src/pci_lmt_bin/main.py
Traceback (most recent call last):
  File "/home/mimir-d/proj/ocp-diag-pci_lmt/src/pci_lmt_bin/main.py", line 16, in <module>
    from pci_lmt import collector
  File "/home/mimir-d/proj/ocp-diag-pci_lmt/src/pci_lmt/collector.py", line 17, in <module>
    from pci_lmt.results import LmtLaneResult, LmtTestInfo, Reporter
  File "/home/mimir-d/proj/ocp-diag-pci_lmt/src/pci_lmt/results.py", line 29, in <module>
    @dc.dataclass
     ^^^^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'pci_lmt.results.LmtTestInfo'> for field test_info is not allowed: use default_factory
```

**Comment by m-charlton** [comment]
I think this is related to this [change](https://docs.python.org/3/whatsnew/3.11.html#dataclasses) in the 3.11 release. I wouldn't mind having a crack at this.

**Comment by mwkm00** [comment]
Did a #4 PR that fixes the issue, you are right @m-charlton.

**Comment by mimir-d** [comment]
thanks for the fix @starswaterbrook
